# -*- coding: utf-8 -*-
"""2D-그래프

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zjY_c-Cc3Dfmc9PiAKbRYH4P2A87OZNI
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-np.pi, np.pi)
y1 = -np.cos(0)*np.cos(x)+0.125*np.cos(2*x)         #그래프 작성할 식
y2 = -np.cos(6)*np.cos(x)+0.125*np.cos(2*x)
y3 = -np.cos(12)*np.cos(x)+0.125*np.cos(2*x)
y4 = -np.cos(18)*np.cos(x)+0.125*np.cos(2*x)
y5 = -np.cos(24)*np.cos(x)+0.125*np.cos(2*x)
y6 = -np.cos(30)*np.cos(x)+0.125*np.cos(2*x)
y7 = -np.cos(36)*np.cos(x)+0.125*np.cos(2*x)
y8 = -np.cos(42)*np.cos(x)+0.125*np.cos(2*x)
y9 = -np.cos(48)*np.cos(x)+0.125*np.cos(2*x)
y10 = -np.cos(54)*np.cos(x)+0.125*np.cos(2*x)
y11 = -np.cos(60)*np.cos(x)+0.125*np.cos(2*x)
y12 = -np.cos(66)*np.cos(x)+0.125*np.cos(2*x)
y13 = -np.cos(72)*np.cos(x)+0.125*np.cos(2*x)
y14 = -np.cos(78)*np.cos(x)+0.125*np.cos(2*x)
y15 = -np.cos(84)*np.cos(x)+0.125*np.cos(2*x)
y16 = -np.cos(90)*np.cos(x)+0.125*np.cos(2*x)

fig, ax = plt.subplots()      #그래프 작성

ax.plot(x, y1)
ax.plot(x, y2)
ax.plot(x, y3)
ax.plot(x, y4)
ax.plot(x, y5)
ax.plot(x, y6)
ax.plot(x, y7)
ax.plot(x, y8)
ax.plot(x, y9)
ax.plot(x, y10)
ax.plot(x, y11)
ax.plot(x, y12)
ax.plot(x, y13)
ax.plot(x, y14)
ax.plot(x, y15)
ax.plot(x, y16)

plt.show()

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-np.pi, np.pi)
b = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
fig, ax = plt.subplots() #이동
for i in b :
  i = i +1
  y= -np.cos(6*i)*np.cos(x)+0.125*np.cos(2*x)   #위에 처럼 함수를 y1,2,3으로 적용이 안되어서 하나의 그래프로 나오지 않는 것 같습니다.
  ax.plot(x, y)

plt.show() # 내어쓰기
