# -*- coding: utf-8 -*-
"""BdGHamiltonian.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aqaTVH-2WA0gGaEFn4jZ9jczCEJYr6In
"""

import numpy as np
#mport matplotlib.pyplot as plt
#from pylab import meshgrid,cm,imshow,contour,clabel,colorbar,axis,title,show

mu = -1.6 #eV
g = 0.03 #eV
deltad = 0.20 #eV
theta = 53.1

def alpha(kx, ky):
  a = 2.0*np.arctan2(kx,ky)
  return a

def gap1(kx, ky):
  gp1 = deltad*np.cos(2*alpha(kx, ky))
  return gp1

def gap2(kx, ky):
  gp2 = deltad*np.cos(2*alpha(kx, ky) -2*theta)
  return gp2 

def E1(kx, ky):
  Energy1 = ((gap1(kx, ky))**2 + (gap2(kx, ky))**2)/2  
  return Energy1

def Xi(kx, ky):
  xi = -2*(np.cos(kx)+np.cos(ky))-mu
  return xi  

def Dk(kx, ky):
  D = np.sqrt((((gap1(kx, ky))**2 - (gap2(kx, ky))**2)**2/4)+g**2*((gap1(kx, ky))**2 + (gap2(kx, ky))**2 + 4*(Xi(kx, ky)**2))-2*g**2*(gap1(kx, ky))*(gap2(kx, ky)))
  return D

def Ep(kx, ky):
  PositiveEnergy = np.sqrt(E1(kx, ky)+(Xi(kx, ky)**2)+g**2+Dk(kx, ky))   #g=30, 크사이 = 60
  return PositiveEnergy

def En(kx, ky):
  NegativeEnergy = np.sqrt(E1(kx, ky)+(Xi(kx, ky)**2)+g**2-Dk(kx, ky))   #g=30, 크사이 = 60
  return NegativeEnergy
